
def exception_init(space, args_w):
    xxx
